### ISSUE TITLE
Worker on mainnet keeps trying to whitelist, can't reclaim funds

### ISSUE THREAD

**Issue by paletas** [EntropicLabs/entropy_worker#1]
So I tried running the worker, it required 10 Luna so I sent it into my account.

It whitelisted on the contract, sending the 10 Luna, but the worker stopped and so I restarted it, upon doing so it requests another 10 Luna. Now I tried checking the contracts on how to recover and came up with the following message, 

`{ 
    "reclaim_deposit": { 
         "public_key": "..." 
    }
}`

Tried executing it on the account, via station, and the simulation fails with _failed to execute message; message index: 0: dispatch: submessages: 0uluna: invalid coins: invalid request_

Anyway I can fix this?

**Comment by AmitPr** [comment]
Hi, the documentation is still being updated, apologies for the confusion. I can hazard a guess as to why the worker is stopping, and why the deposit is unable to be claimed.

The worker is probably error-ing because by default, it tries whitelisting two keys. This was intentional, although I can see now that it's not intuitive, so reconsidering.

The beacon is instantiated with a `refund_increment_amt` parameter. Every time this key is used to fund a request, the amount (out of 10 luna) that you can reclaim from your key deposit is incremented by this amount. On mainnet, this means that after 10 requests, you would be able to reclaim the full amount.

Unfortunately that mean I can't help you reclaim your deposit without updating the beacon to add a "admin" control to unwhitelist and return a full deposit. I do think, however, that this will be my next item of action to implement, since it seems like an acceptable way to recover mistakenly whitelisted keys. I'll be able to unwhitelist your key, and return your deposit to you once this is implemented.

Apologies for the lack of documentation. The worker-hosting side of the project is still under finishing touches, as the launch was mainly geared towards SC devs. The worker is also being upgraded to have more "helpful" errors as well as more reasonable defaults.

**Comment by AmitPr** [comment]
Fixed with latest documentation changes, worker changes, and a refund.

**Comment by paletas** [comment]
Appreciate the quick explanation, updates and refund.
